### ISSUE TITLE
Start the process after it dies

### ISSUE THREAD

**Issue by onemanstartup** [DarthSim/overmind#10]
"Overmind allows a specified process to die without interrupting all of the other ones;"

But how to start them? If I start in another tab ".overmind.sock: bind: address already in use"
Also would it be cool if you can call commands in overmind tui and start restart connect to process right there, not in new tab/window.

**Comment by DarthSim** [comment]
Restarting died processes added to the latest release https://github.com/DarthSim/overmind/releases/tag/v1.0.9. You can restart them with `overmind r died_process_name` just like live ones.
PR to Homebrew is waiting for merge Homebrew/homebrew-core#20917

**Comment by joekur** [comment]
Would you consider an option to auto-restart a dead process? Eg instead of `overmind s -c foo`, you could do for example `overmind s -r foo` (where `r` might mean "auto restart on death"), and if it dies overmind would automatically restart it anew?
