### ISSUE TITLE
overmind: Can't find tmux.

### ISSUE THREAD

**Issue by Morgan-jarry** [DarthSim/overmind#101]
I'm on MacOS 10.15.7 and I installed `overmind` from `brew` which install `tmux` dependencies automatically.
```sh
$ which tmux
/usr/local/bin/tmux
```
```sh
$ tmux -V
tmux 3.1c
```
```sh
$ overmind -v
Overmind version 2.2.0
```
But when I try to launch `overmind s`, I still get the error:
```
overmind: Can't find tmux. Did you forget to install it?
```

**Comment by Morgan-jarry** [comment]
Ok, so I found out overmind doesn't work when the command is nested inside `if…else` condition.
That's weird. Maybe the way you check `tmux` is installed is not good ? ¯\_(ツ)_/¯

**Comment by DarthSim** [comment]
As you can see, Overmind just runs `which tmux`, no fancy stuff: https://github.com/DarthSim/overmind/blob/master/start/command.go#L177. I don't know a better way to check its existence.

**Comment by sshkarupa** [comment]
@Morgan-jarry Hey. Did you solve this issue? I've got the same error and don't understand what's wrong.

**Comment by Morgan-jarry** [comment]
@sshkarupa Not at all. I had to remove the `if…else` condition to make it works…

**Comment by DarthSim** [comment]
v2.2.1 checks tmux with `tmux -V` instead of `which tmux`. Hope this will help.

**Comment by Morgan-jarry** [comment]
Fix by https://github.com/DarthSim/overmind/releases/tag/v2.2.1

**Comment by Morgan-jarry** [comment]
@DarthSim thank you for the fix !
