### ISSUE TITLE
Show process status and/or command to query for process status

### ISSUE THREAD

**Issue by holic** [DarthSim/overmind#108]
I have a Procfile with ~10 processes that throw out a lot of output. Sometimes one will crash, but I'll miss the log lines and something weird in my app will break. It takes me a bit of time to figure out which service broke/which to restart.

It'd be great if Overmind had some static line at the bottom of the logs that reported the status of each process, e.g.
```
frontend | example log line
backend  | example log line
api      | example log line
[api] [backend] [frontend]
```

Where each of the `[process]` indicators could be color coded for status (e.g. green for up and red for down).

Alternatively, or additionally, it'd be nice to have a `overmind status backend` or similar to find out if an Overmind-managed process is up or down. Then I could build some of my own tooling for the status bar that I want.

**Comment by samtgarson** [comment]
+1 for this, I leave my processes running in the background with auto-restart turned on, but sometimes I forget whether I killed it before lunch or if they're still running, or often want to check if one has indeed crashed.

Short of `echo`ing and exiting again, there seems to be no way of doing this—an `overmind status` command would be super useful.

@DarthSim would you accept a PR for this?

**Comment by DarthSim** [comment]
@samtgarson sure, PRs are always welcome :)

**Comment by DarthSim** [comment]
Added `overmind ps` to `v2.3.0`

**Comment by samtgarson** [comment]
Great, thanks! 🎉

**Comment by holic** [comment]
Thank you! 🙌
