### ISSUE TITLE
High Sierra, overmind no longer exits cleanly

### ISSUE THREAD

**Issue by jemmyw** [DarthSim/overmind#11]
Since upgrading to High Sierra from Sierra, overmind no longer exits.

Processes start fine. When interrupting with ctrl+c the processes all appear to be interrupted and exit, but overmind does not stop.

```
> ps -e|grep overmind

60631 ??         0:00.10 tmux new -d -s overmind-xxx-B0JuToCv8O2nRqVpCe8dgaGg2nw2Wwk4 -x 80 -y 57 -n web -P -F #{pane_pid} overmind launch web bundle exec unicorn -p 3000 -c ./config/unicorn_dev.rb 5000 /Users/jeremy/src/xxx/.overmind.sock \; allow-rename off
60627 ttys000    0:00.72 overmind s
60632 ttys008    0:00.20 overmind launch web bundle exec unicorn -p 3000 -c ./config/unicorn_dev.rb 5000 /Users/jeremy/src/xxx/.overmind.sock ; allow-rename off
```

**Comment by DarthSim** [comment]
I currently use High Sierra but my team and I can't reproduce the issue. It's a silly question, but are you sure you're not running another instance of overmind?

**Comment by jemmyw** [comment]
Sorry, I feel bad that I didn't come back with the solution. As it turns out, this was a problem with an older version of unicorn. Now, I still feel that there was an issue somewhere in the way overmind was handling it, but since updating to the latest unicorn the problem has gone away.

**Comment by DarthSim** [comment]
No problem. Glad it works fine now :)
