### ISSUE TITLE
Overmind Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mihtoa** [DarthSim/overmind#117]
Hello! 

I'm triyng to install Overmind in my system but when I try to execute the file it's show the error:
```
Segmentation fault (core dumped)
```
I already install **tmux** and now I'm triyng to install the **overmind-v2.2.2-linux-amd64.gz** release.
I already try too install using Go but same happens.

Someone know why is this happening? Heeelp

My system is Ubuntu 20.04.3 LTS

Thanks!

**Comment by mihtoa** [comment]
Updating the case, I managed to solve the installation following the question in #65.

```
sudo curl -L https://github.com/DarthSim/overmind/releases/download/v2.2.2/overmind-v2.2.2-linux-amd64.gz > overmind.gz
gunzip overmind.gz
sudo mv overmind /usr/local/bin
chmod +x /usr/local/bin/overmind
```

**Comment by DarthSim** [comment]
Hey Milene!
Glad you solved this! If anything goes wrong again, please include the whole error log :)
