### ISSUE TITLE
Allow to specify custom env file

### ISSUE THREAD

**Issue by smileart** [DarthSim/overmind#12]
Basically, if one has more than one `.env` file, it'd be great to be able to specify which file to use (i.e. foeman's `-e` option). Moreover, maybe I'm wrong, but when you have more than one project the global `~/.overmind.env` seems to be quite a weird solution.

**Comment by hkrutzer** [comment]
I was just about file a similar issue. All my colleagues use Foreman, which reads `.env`. It would be great if Overmind could read `.env` or has a flag to read any env file.

**Comment by DarthSim** [comment]
Overmind reads `.overmind.env` both from your home directory and working directory. But maybe it would be good to let you specify `.env` file and read env from `.env` in the working dir. I'll think about this.

**Comment by DarthSim** [comment]
Support of `.env` in the current directory and support of custom env file path are added to the latest release https://github.com/DarthSim/overmind/releases/tag/v1.0.9
PR to Homebrew is waiting for merge https://github.com/Homebrew/homebrew-core/pull/20917

**Comment by DarthSim** [comment]
Note: flags are parsed before reading env files, so it's possible to specify custon env file only with env variable: `OVERMIND_ENV=path/to/your/file overmind s`

**Comment by smileart** [comment]
@DarthSim Awesome! Thanks a lot. It'd be great to update README.md as well, mentioning `OVERMIND_ENV` I think, but generally — brilliant. Cheers! 👍

**Comment by DarthSim** [comment]
Yup, you're right. Updated
