### ISSUE TITLE
Add ability to use `overmind connect` with no argument

### ISSUE THREAD

**Issue by maschwenk** [DarthSim/overmind#124]
I tried attempting this myself but had some issues. It would be nice to run `overmind connect` without an argument and have overmind connect to some arbitrary process (or the first one that's defined). Sometimes it's nice to not have to remember exactly the names of all the processes.

**Comment by DarthSim** [comment]
Hey @maschwenk!
Added this feature to `v2.3.0`

**Comment by maschwenk** [comment]
@DarthSim Thank you so much!
