### ISSUE TITLE
Supports multiple environment overrides

### ISSUE THREAD

**Issue by scalp42** [DarthSim/overmind#125]
Hey @DarthSim 

Thanks for the project!

Would you be open to add the feature of environment overloading?

For example:

```
-e .env,.env.prod,.env.prod
```

Where the last file inserts/upserts whatever ENV var exist.

Hopefully it makes sense but let me know.

Cheers!

**Comment by DarthSim** [comment]
Hey @scalp42!
`v2.3.0` allows `OVERMIND_ENV` to contain multiple file paths

**Comment by scalp42** [comment]
@DarthSim thanks a lot! 

If a file path doesn't exist, does it just skip it without breaking? Ideally it just warns or something but wondering.

**Comment by DarthSim** [comment]
It just skips it
