### ISSUE TITLE
Cannot debug rails with overmind

### ISSUE THREAD

**Issue by navjeetc** [DarthSim/overmind#126]
When try to debug my rails app with overmind it does not stop at the line of code where debugger has been specified. This is a Rails 7 app (Jumpstart Pro). Here is a short video I made of the steps I am performing. Can anybody tell me what am I doing wrong?
https://www.loom.com/share/313fb00197904bba9127d8562fbc99f6?sharedAppSource=personal_library

**Comment by DarthSim** [comment]
Hi @navjeetc! Overmind can't affect Ruby breakpoints, so it doesn't look like an Overmind issue.

**Comment by navjeetc** [comment]
You are correct @DarthSim . The issue was one modification I had made to puma.rb `stdout_redirect "log/puma.stdout.log", "log/puma.stderr.log"` which now makes sense. Once I comment that line all is good.
