### ISSUE TITLE
go get: installing executables with 'go get' in module mode is deprecated.

### ISSUE THREAD

**Issue by kobusjoubert** [DarthSim/overmind#128]
Hi, I got this error while running `GO111MODULE=on go get -u github.com/DarthSim/overmind/v2` as instructed on the [README](https://github.com/DarthSim/overmind/#build-overmind-from-source) when building from source.

```
bash-5.1# GO111MODULE=on go get -u github.com/DarthSim/overmind/v2
go: downloading github.com/DarthSim/overmind/v2 v2.2.2
go: downloading github.com/DarthSim/overmind v2.0.1+incompatible
go: downloading github.com/urfave/cli v1.22.2
go: downloading github.com/DarthSim/godotenv v1.3.1
go: downloading github.com/matoous/go-nanoid v0.0.0-20181114085210-eab626deece6
go: downloading github.com/sevlyar/go-daemon v0.1.5
go: downloading github.com/urfave/cli v1.22.9
go: downloading golang.org/x/crypto v0.0.0-20190411191339-88737f569e3a
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading golang.org/x/sys v0.0.0-20190403152447-81d4e9dc473e
go: downloading github.com/matoous/go-nanoid v1.5.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading golang.org/x/crypto v0.0.0-20220517005047-85d78b3ac167
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading golang.org/x/sys v0.0.0-20220513210249-45d2b4557a2a
go: downloading github.com/russross/blackfriday v1.6.0
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading golang.org/x/term v0.0.0-20201126162022-7de9c90e9dd1
go: downloading golang.org/x/term v0.0.0-20220411215600-e5f449aeb171
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

Using 'go install' instead of 'go get' worked for me `GO111MODULE=on go install github.com/DarthSim/overmind@v2`.

```
bash-5.1# GO111MODULE=on go install github.com/DarthSim/overmind@v2
go: finding module for package gopkg.in/urfave/cli.v1
go: finding module for package github.com/pkg/term/termios
go: finding module for package github.com/joho/godotenv
go: finding module for package github.com/matoous/go-nanoid
go: downloading gopkg.in/urfave/cli.v1 v1.20.0
go: downloading github.com/joho/godotenv v1.4.0
go: downloading github.com/pkg/term v1.1.0
go: found github.com/joho/godotenv in github.com/joho/godotenv v1.4.0
go: found gopkg.in/urfave/cli.v1 in gopkg.in/urfave/cli.v1 v1.20.0
go: found github.com/matoous/go-nanoid in github.com/matoous/go-nanoid v1.5.0
go: found github.com/pkg/term/termios in github.com/pkg/term v1.1.0
go: downloading golang.org/x/sys v0.0.0-20200909081042-eff7692f9009
bash-5.1# 
```

Just incase somebody else had the same issue 🙂

**Comment by kobusjoubert** [comment]
Also worth mentioning, this was on a Docker image `ruby:3.1.1-alpine`. Running `GO111MODULE=on go get -u github.com/DarthSim/overmind/v2` on `ruby:2.7.6-bullseye` works fine.

**Comment by josersjq** [comment]
I just did the this one instead:
```
GO111MODULE=on go install github.com/DarthSim/overmind/v2@latest
```

**Comment by DarthSim** [comment]
Thanks for pointing this out. Fixed instructions in README

**Comment by ricardopacheco** [comment]
@DarthSim This works, but not as expected!

When i run `go install github.com/DarthSim/overmind@latest`, i expected overmind version 2.3.0, but, the version 2.0.1 is installed.

```
➜  ~ go install github.com/DarthSim/overmind@latest
go: finding module for package github.com/pkg/term/termios
go: finding module for package github.com/joho/godotenv
go: finding module for package github.com/matoous/go-nanoid
go: finding module for package gopkg.in/urfave/cli.v1
go: found github.com/joho/godotenv in github.com/joho/godotenv v1.4.0
go: found gopkg.in/urfave/cli.v1 in gopkg.in/urfave/cli.v1 v1.20.0
go: found github.com/matoous/go-nanoid in github.com/matoous/go-nanoid v1.5.0
go: found github.com/pkg/term/termios in github.com/pkg/term v1.1.0
➜  ~ overmind --version
Overmind version 2.0.1
```

**Comment by elalemanyo** [comment]
@kobusjoubert I am trying to run overmind inside Docker but I am getting this error: `bash: line 1: /tmp/overmind-rails-e1HZJiQCLzF9v2K1yb6vT/tailwind: Permission denied` https://github.com/DarthSim/overmind/issues/136
Maybe you can help me with that 🙂 Thanks

**Comment by kobusjoubert** [comment]
Hi @elalemanyo, I'm not sure how you use `overmind` with Docker, I used it for a `localhost` setup with different services defined in the `Procfile`. When I'm using Docker I don't use `overmind` for the different processes, I use containers for the different services. Something like this here https://github.com/kobusjoubert/rails_dockerize/blob/a19df380e03524f0fe420632b4455425b96c6b71/docker-compose.yml#L34

**Comment by elalemanyo** [comment]
> Hi @elalemanyo, I'm not sure how you use `overmind` with Docker, I used it for a `localhost` setup with different services defined in the `Procfile`. When I'm using Docker I don't use `overmind` for the different processes, I use containers for the different services. Something like this here https://github.com/kobusjoubert/rails_dockerize/blob/a19df380e03524f0fe420632b4455425b96c6b71/docker-compose.yml#L34

I understand, but what is the benefit of having so many services when you could do it all in one 🤔
