### ISSUE TITLE
Ability to run arbitrary commands

### ISSUE THREAD

**Issue by bpatram** [DarthSim/overmind#13]
In foreman (http://ddollar.github.io/foreman/#SYNOPSIS) you can execute `foreman run some_command_here` which will set the environment variables defined in the `.env` file and run `some_command_here`. Sometimes this is useful if you store npm or rubygem configurations (`NPM_CONFIG_REGISTRY`) in a .env file and you want to run `yarn install` or `bundle install`.

There doesn't seem to be an equivalent feature in Overmind. Is this functionality possible, if not, would it make sense to add this in?

---
Example/Expectation:

```
// .env
NPM_CONFIG_REGISTRY=https://npm.fury.io/TOKEN/USERNAME
```
Running `overmind run yarn install` should set the env vars defined for the `yarn install` process when it runs just like `foreman run yarn install` would. Doing so would not start and execute the items defined in your `Procfile` of course.

**Comment by DarthSim** [comment]
Added to [v2.0](https://github.com/DarthSim/overmind/releases/tag/v2.0.0)
