### ISSUE TITLE
Start overmind using an existing, currently-running tmux server

### ISSUE THREAD

**Issue by fnune** [DarthSim/overmind#138]
I want to jump to/from the `overmind connect` server/session to my other sessions launched in a different tmux server. The command `overmind connect` launches its own tmux server, though, so when I list sessions in my original server, Overmind doesn't show inside it.

Is there any way to point Overmind at my existing server when launching it?

**Comment by DarthSim** [comment]
Overmind used to use the existing tmux server to run its sessions but I had to switch to the current behavior. I don't remember the exact reason as it was a very long time ago, but as far as I remember it was related to environment variables and stuff. I'd rather not change things that work. Hope you understand.

**Comment by fnune** [comment]
:+1: just curious: could you point me to the commit where that change happened? If it's not too much of a hassle.

Closing this issue, thanks for your time, and thanks for Overmind! :bow:
