### ISSUE TITLE
How to specify start order

### ISSUE THREAD

**Issue by polRk** [DarthSim/overmind#139]
Like in docker-compose i can specify 

```
depends_on:
  {{PROCESS}}:
    condition: service_started
```

**Comment by DarthSim** [comment]
Procfile is a very simple format that doesn't support health checks. Applications that use it can't determine the readiness of processes and thus can't make processes wait for their dependencies' readiness.

**Comment by gedw99** [comment]
Yeah I normally make each process that connects to another process have an exponential back off / retry.

mots good practice too . Never know what is going on under the covers so best to be pessimistic

**Comment by chriscz** [comment]
You could probably hack this by putting in a sleep for a few milliseconds: `web: sleep 0.5 && server start`, there are alternative approaches like testing if a port is open: `nc -w 0.5 "${host}" "${port}" < /dev/null &> /dev/null`
