### ISSUE TITLE
Having some strange issues with .env loading

### ISSUE THREAD

**Issue by scharfie** [DarthSim/overmind#14]
The loading of .env in 1.0.9 is causing some strange issues for me.  I use dotenv with rails, in which you have a base `.env`, and then environment-specific files such as `.env.development` or `.env.production` for overriding certain variables depending on which application environment you want to boot.  The issue I'm seeing is that, no matter what, only the `.env` variables are loading.  Even if I specify using `OVERMIND_ENV`, the variables in `.env.development` do not load.

Here's a very distilled example that shows the issue:

```
# .env
FILENAME=.env
```
```
# .env.development
FILENAME=.env.development
```

```
# Procfile
echo: echo Filename is $FILENAME
```

```
$ overmind s
echo   | Started with pid 9639...
echo   | Filename is .env
echo   | Exited

$ OVERMIND_ENV=./.env.development overmind s
echo   | Started with pid 9699...
echo   | Filename is .env
echo   | Exited
```

Am I doing something wrong?

**Comment by DarthSim** [comment]
Hi!
It happens because of the way tmux works with ENV variables. The latest release should work fine, please, check it out.

Note that this release is not compatible with previous ones, so you'll need to restart running overmind instances.

**Comment by scharfie** [comment]
Thanks :)  New release seems to be working 👍
