### ISSUE TITLE
Gracefully handle backgrounded processes

### ISSUE THREAD

**Issue by mculp** [DarthSim/overmind#143]
Kinda similar to some of the other issues on here. `rubocop --start-server` always runs daemonized, which kills the other processes. In this case, there's no signal to trap, since it's just spawning another process.

Hopefully the issue will be remedied soon on their side soon, as they have a pull request open: https://github.com/rubocop/rubocop/pull/11319

But I think a lot of folks would benefit from some type of solution for this -- whether it's before/after hooks, process order, process dependencies, or something else.

My workaround:

`OVERMIND_CAN_DIE=rubocop rubocop --start-server`

This isn't a great workaround, because the server continues running even after Overmind has shutdown.

<img width="236" alt="image" src="https://user-images.githubusercontent.com/129983/210306686-359a68e0-620d-4288-9a68-da1c2627df52.png">

But you can see the rubocop server running:

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/129983/210307197-d22064ee-f038-4e04-b29d-a89fa98fa120.png">

Here, you can see all processes running:
(I guess it's a separate issue, but there are two of each of them)
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/129983/210306949-c26c4ab5-1859-48ed-b02e-04803cd9d93c.png">

After `overmind stop`:
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/129983/210307369-3b6b2f46-5091-4c24-9a99-9ca87c8ffaf7.png">

**Comment by DarthSim** [comment]
Unfortunately, I don't see any way to fix this on the Overmind's level. When daemonizing, the process launches another process within another process group. Thus Overmind can't get the new process's PID and can't monitor its status.

As a dirty bypass:

```
rubocop: trap 'rubocop --stop-server' EXIT > /dev/null; rubocop --start-server && ping localhost > /dev/null
```

`trap 'rubocop --stop-server' EXIT > /dev/null` sets the trap on exit so `rubocop --stop-server` will be executed when the script exits.
`ping localhost > /dev/null` makes script keeping running after `rubocop --stop-server` exits.

**Comment by mculp** [comment]
agh! That ping trick worked! But that is definitely a dirty, dirty bypass :)

Thank you.
