### ISSUE TITLE
Not working well with ngrok

### ISSUE THREAD

**Issue by JiProchazka** [DarthSim/overmind#15]
Hi,

overmind is not working well with ngrok.
My proc file is:

    rack: rackup
    ngrok: ngrok http 9292

When running ngrok (by `overmind start`)
![1](https://user-images.githubusercontent.com/17881279/34044893-212045b6-e1a7-11e7-8459-9cab3cf91ba1.png)

When the overmind is stopped:
![2](https://user-images.githubusercontent.com/17881279/34044928-47919d26-e1a7-11e7-8658-bffb5a889726.png)

How it should look like when ngrok started manually with `ngrok http 9292`:
![3](https://user-images.githubusercontent.com/17881279/34044949-5d76268e-e1a7-11e7-9594-5bde09ef4a57.png)

The problem is I can't see the urls ngrok is hooked to untill I stop the overmind.

Thanks

**Comment by DarthSim** [comment]
Hi. I would better say "ngrok doesn't work well with overmind" :) Ngrok uses whole term by default and rewrites overmind's output. You can change this behavior this way: `ngrok http 9292 --log stdout`. When ngrok is running, you can find URLs and other info on it's dashboard - http://localhost:4040/
