### ISSUE TITLE
Auto-restart all processes?

### ISSUE THREAD

**Issue by dunkmann00** [DarthSim/overmind#153]
Hello! I have just started using overmind with much enjoyment. I was wondering if you would be open to adding the option to auto-restart all processes? I think this would be similar to how `--any-can-die` allows any process to die, there could be a `--auto-restart-all' flag to tell overmind to restart all processes if they die.

**Comment by DarthSim** [comment]
Hi @dunkmann00!
PRs are always welcome 😉

**Comment by dunkmann00** [comment]
Awesome! I've been wanting to learn Go for a while so this seems like a good excuse to do so!

**Comment by lambrospetrou** [comment]
I just wanted this as well 😅 I didn't want to use yet another process supervising tool, so a `overmind start -r all` kind of thing would be nice indeed.
