### ISSUE TITLE
Hint to remove .overmind.sock

### ISSUE THREAD

**Issue by joekur** [DarthSim/overmind#16]
In some cases you can have a leftover `.overmind.sock` file but without a running overmind process. I think in my case this was caused by a computer restart while it was running. It would be nice if the error you get when trying to reboot overmind would prompt you to remove the file if you know that it's not currently running.

Current message:
> overmind: listen unix /Users/joekur/dev/reverb/.overmind.sock: bind: address already in use

As an example, zeus (https://github.com/burke/zeus) gives this message:
> Unable to accept socket connection.
> It looks like Zeus is already running. If not, remove .zeus.sock and try again.

**Comment by DarthSim** [comment]
Good point, thanks!

**Comment by PrimeTimeTran** [comment]
YES!!!!

**Comment by PrimeTimeTran** [comment]
Yes please, this tool is awesome but I cannot figure out a way to kill the socket =(
![screen shot 2018-01-12 at 12 49 55 am](https://user-images.githubusercontent.com/16382165/34838952-890178da-f732-11e7-9091-aa40d2bdc694.jpg)

**Comment by joekur** [comment]
@PrimeTimeTran have you removed the sock file and retried? `rm .overmind.sock`

**Comment by PrimeTimeTran** [comment]
@joekur that solved it. Thanks. I  tried every imaginable combination of killing and restarting.

**Comment by DarthSim** [comment]
The latest release shows better message when socket is in use

**Comment by ArinzeJeffrey-droid** [comment]
@joekur it works, thanks.

**Comment by yshmarov** [comment]
> @PrimeTimeTran have you removed the sock file and retried? `rm .overmind.sock`

worked for me. Thanks!

**Comment by felipemelendez** [comment]
> @PrimeTimeTran have you removed the sock file and retried? `rm .overmind.sock`

thank you!

**Comment by acushlakoncept** [comment]
> @PrimeTimeTran have you removed the sock file and retried? `rm .overmind.sock`

Thank you, worked for me
