### ISSUE TITLE
How to clear our tmux if overmind thinks its already running?

### ISSUE THREAD

**Issue by drnic** [DarthSim/overmind#164]
After MacOS upgrade, and even a fresh reboot, overmind thinks my app is still running. There is no `.overmind.sock` file. I think my question is: how can I clear our tmux so overmind will run?

```
$ overmind start -f Procfile.dev
system | Tmux socket name: overmind-dummy-app-KlF4Fc0-yjElSRXZBuQim
system | Tmux session ID: dummy-app
system | Listening at ./.overmind.sock
overmind: it looks like Overmind is already running. If it's not, remove ./.overmind.sock and try again
```

**Comment by DarthSim** [comment]
Hi @drnic!
Files with filenames started with dot are hidden in *nix systems. You can see them with `ls -a`. Just run `rm -rf ./.overmind.sock` to delete the socket.

**Comment by drnic** [comment]
Ahh, the problem was my wrapper command `bin/dev` was going into another folder before running overmind. So the .overmind.sock file was in the subfolder and I forgot. Damnit. Thanks @DarthSim for overmind 👍🏽
