### ISSUE TITLE
Аналог команды kill для SIGINT? 

### ISSUE THREAD

**Issue by alekseyl** [DarthSim/overmind#17]
Может реализовать команду stop как аналог Ctrl + C, а то в ряде случаев детишки сиротками остаются. 

В частности вот было у pumы пара рабочих котят, если послать overmind kill, котятки-то разбегутся, и потом не запустишься пока не передушишь их ручками. 

Не то, чтобы прям кушать не получается без этой команды, но как же котятки?

**Comment by DarthSim** [comment]
`kill` предназначена для крайних случаев, когда все совсем плохо и нужно жестко погасить tmux-сессию. Пользоваться этой командой на постоянной основе не стоит по описанным причинам. Overmind прекрасно понимает Ctrl-C и вежливо останавливает ту же пуму.
