### ISSUE TITLE
Is this gem related to this project?

### ISSUE THREAD

**Issue by stephannv** [DarthSim/overmind#175]
I'm reviewing a PR where this `overmind` gem is being added, but I'm not sure if I can trust it since it isn't listed as an installation method on README.md, but at same time its home page points to this repo.
https://rubygems.org/gems/overmind

**Comment by Envek** [comment]
Yes, it is a work in progress to package both overmind and tmux as a Ruby gem by our own @prog-supdex.

Will add build code and installation instructions here soon.

Thanks for your vigilance

**Comment by Envek** [comment]
Ruby gem related stuff was added in #176 and released in [2.5.0](https://github.com/DarthSim/overmind/releases/tag/v2.5.0), and also matching version has been released to Rubygems, please enjoy.

**Comment by stephannv** [comment]
> Ruby gem related stuff was added in #176 and released in [2.5.0](https://github.com/DarthSim/overmind/releases/tag/v2.5.0), and also matching version has been released to Rubygems, please enjoy.

Thanks fellows.
