### ISSUE TITLE
Error when running `go install github.com/DarthSim/overmind/v2@latest` w/in a repo that uses it.

### ISSUE THREAD

**Issue by jasondborneman** [DarthSim/overmind#177]
Our repo has a `/setup` script that installs requirements, one of which is `overmind` (`go install github.com/DarthSim/overmind/v2@latest`). It runs this within our repo. This worked fine until the replace directive was added into `overmind`'s `go.mod`: https://github.com/DarthSim/overmind/blob/master/go.mod#L20

Now when trying to run our setup it bombs out when reaching the `overmind` install step with the following error:

```
go: github.com/DarthSim/overmind/v2@latest (in github.com/DarthSim/overmind/v2@v2.5.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

In fact, I tried running `go install github.com/DarthSim/overmind/v2@latest` even outside our repo and still get that same error.

We are on go version `1.22.1`, btw

**Comment by Envek** [comment]
This golang limitation is freaking me out: https://github.com/golang/go/issues/44840

But anyway, removed replace directive and tagged [2.5.1](https://github.com/DarthSim/overmind/releases/tag/v2.5.1) so it should work now, thanks for reporting.

**Comment by jasondborneman** [comment]
> This golang limitation is freaking me out: [golang/go#44840](https://github.com/golang/go/issues/44840)
> 
> But anyway, removed replace directive and tagged [2.5.1](https://github.com/DarthSim/overmind/releases/tag/v2.5.1) so it should work now, thanks for reporting.

Can confirm this fixed our issue. Thanks! 🎉
