### ISSUE TITLE
Restarting a process is not working on some termination conditions.

### ISSUE THREAD

**Issue by offbyone** [DarthSim/overmind#190]
Overmind: v2.5.1
OS: macOS Sequoia 15.1.1

I have a Procfile with a command that connects to a GitHub codespace for port forwarding:

```
port-forward: gh cs --codespace $(script/get-codespace-id) ports forward 80:3080 3035:3035
ngrok: ...
```

I have configured that service to be allowed to die and to restart:

```
OVERMIND_CAN_DIE=port-forward,shell,console
OVERMIND_AUTO_RESTART=port-forward,shell,console
```

When I have a network interruption, though, the process dies, and is not restarted:

```shellsession
$ overmind status
PROCESS            PID       STATUS
port-forward       12497     dead
ngrok              84235     running
```

Connecting to the `port-forward` process shows this:

```
Forwarding ports: remote 3035 <=> local 3035
Forwarding ports: remote 80 <=> local 3080
error connecting to tunnel: connect to forwarded port failed: error connecting to forwarded port: failed to open streaming channel: failed to open port forward channel: failed to open channel: read tcp 192.168.5.148:64831->20.69.79.91:443: read: can't assign requested address
```

... and that's it. It doesn't restart, which is what I expect given the configuration.

**Comment by DarthSim** [comment]
Hey @offbyone!

You should not use `OVERMIND_CAN_DIE` in this situation.

Processes in the `OVERMIND_CAN_DIE` list can die without any consequences. Their termination won't cause the termination of the rest of the processes, nor will Overmind restart them.

`OVERMIND_AUTO_RESTART` == "if it dies, try to revive it"
`OVERMIND_CAN_DIE` == "if it dies, let it be dead"

**Comment by offbyone** [comment]
TIL! Thanks!
