### ISSUE TITLE
Support Procfile.local

### ISSUE THREAD

**Issue by dlibanori** [DarthSim/overmind#20]
It would be nice to also load a local procfile. I work with a Mac, my coworker with Linux, I need to start redis, she doesn't. We write one Procfile with common services, save it on git, I write Procfile.local with redis and ignore it in git. What do you think?

**Comment by DarthSim** [comment]
Hi. My team and I are in a similar situation: we have one Procfile for production and another one for development. I solved this with built-in features of Overmind: I just created `.overmind.env` file (ignored by git) with `OVERMIND_PROCFILE=Procfile.dev`. Now Overmind uses `Procfile.dev` by default.

**Comment by dlibanori** [comment]
It would be useful to move your comment to README.md
