### ISSUE TITLE
Tmux cannot create window in v1.1.0

### ISSUE THREAD

**Issue by klappradla** [DarthSim/overmind#21]
Hi 👋 

first of all: million thanx for this awesome project 💯 

With upgrading `overmind` to the latest version `1.1.0` I can no longer start my services - I suspect this is due to the changes in how you changed starting tmux servers 🤔 _(I'm running tmux version `2.6`)_

I get this tmux error:
```
create window failed: index in use: 0
````

My `Procfile` is pretty basic _(as the error let's says, it fails on the 2nd item: redis)_:
```
web: rails s -p 3000
redis: redis-server
sidekiq: bundle exec sidekiq -C config/sidekiq.development.yml
webpacker: bundle exec rake react_on_rails:locale && ./bin/webpack-dev-server
```

Am I doing anything wrong? I for now downgraded to `1.0.9`...

**Comment by DarthSim** [comment]
Hi! Don't know how it worked all the time for the most of users, but somehow it did. Please check out the latest release, it should solve the problem. (Will be in Homebrew soon)

**Comment by klappradla** [comment]
💚 thanx a ton for the quick answer and fix 🎉  _(funny that it's after all only a single character)_

I'll close this issue once the new version is available on Homebrew and I checked it 🕵️

**Comment by DarthSim** [comment]
It should be available now

**Comment by klappradla** [comment]
Yay, all fine again 🤗 

Thanx!
