### ISSUE TITLE
Session not visible in tmux session list

### ISSUE THREAD

**Issue by thejspr** [DarthSim/overmind#22]
When starting overmind, I used to see the tmux session the list of sessions, but it's not showing anymore. This is the boot output:

```
system      | Listening at /Users/thejspr/Code/reklameskyen/.overmind.sock
system      | Tmux socket name: overmind-reklameskyen-5pDERsrSCEJLRsh7z~dSqK
system      | Tmux session ID: reklameskyen
```

Is this a known bug or an intentional change?

I'm using version Overmind v1.1.1, Tmux 2.6 on MacOS High Sierra.

**Comment by DarthSim** [comment]
Hi. Overmind starts its own tmux server on the listed socket:

```
system      | Tmux socket name: overmind-reklameskyen-5pDERsrSCEJLRsh7z~dSqK
```

This allows not to mess environment with other tmux sessions and solves a lot of issues. If you want to list overmind's sessions, you can use `-L` like this:

```
tmux -L overmind-reklameskyen-5pDERsrSCEJLRsh7z~dSqK list-sessions
```

**Comment by thejspr** [comment]
I much preferred the previous behaviour but understand it's a tradeoff. Do you have any tips to easily connect to the overmind session without nesting tmux'es?
