### ISSUE TITLE
Feature request: restart all

### ISSUE THREAD

**Issue by jemmyw** [DarthSim/overmind#26]
I sometimes need to restart everything, it'd be cool to say:

`overmind r *`

which would fit with the filters idea someone else posted. `overmind r web*` for example.

**Comment by DarthSim** [comment]
If you want to restart all processes, you can restart overmind itself.

**Comment by gee-forr** [comment]
I'd love it if issuing `overmind restart` without further params would assume i want all managed processes restarted.

P.S - Thank you Sergey for this amazing piece of software. I've only been using it for a day, but it's already made my life easier.

**Comment by DarthSim** [comment]
Added to [v2.0](https://github.com/DarthSim/overmind/releases/tag/v2.0.0)

Now `restart` supports wildcarded names. When no names are provided, all processes will be restarted
