### ISSUE TITLE
PORT variable gets overwritten by OVERMIND_PORT

### ISSUE THREAD

**Issue by harmdewit** [DarthSim/overmind#3]
It seems like the PORT variable is overwritten by the OVERMIND_PORT variable, which is confusing.

```
# .overmind.env
PORT=3000 # doesn't work, results in the default 5000
```

Setting the OVERMIND_PORT variable directly does work

```
# .overmind.env
OVERMIND_PORT=3006 # does work
```

**Comment by DarthSim** [comment]
It's not quite an issue, but a feature. I should probably mention it in the README.

Overmind sets the `PORT` variable for each process, so you can do something like this:

```
web: my_web_server -p $PORT
```

Overmind sets `PORT` as `OVERMIND_PORT` for the first process and increases it by `OVERMIND_PORT_STEP` for every next one. If you want to specify PORT for the specific process, you may want to do something like this:

```
web: PORT=3000 my_web_server
```

**Comment by prikha** [comment]
This is an obstacle in the way of interchangeability so to say.
