### ISSUE TITLE
document order of env files

### ISSUE THREAD

**Issue by davidkarlsen** [DarthSim/overmind#30]
Docs say:
"If you need to set specific environment variables before running a Procfile, you can specify them in the .overmind.env file in the current working directory, your home directory, or/and in the .env file in in the current working directory. The file should contain variable=value pairs, one per line:"

Could you document in which order files will be read, as this has importance if https://github.com/DarthSim/overmind/issues/27 gets implemented. 

Also if defining the same variable in several files (and hence overwriting/redefining it) - this has importance.

**Comment by DarthSim** [comment]
Done
