### ISSUE TITLE
"width too small" error

### ISSUE THREAD

**Issue by davidkarlsen** [DarthSim/overmind#31]
I have an utterly strange situation.

If I run:
```
docker run -ti myimage
```

it will run fine, but if I do
```
docker create --name somename -t myimage
```

it will always fail with:
```
system | Listening at /app/.overmind.sock
system | Tmux socket name: overmind-app-VfOudhxLnV5Al0JUBqvAlq
system | Tmux session ID: app
web    | width too small
web    | 
```

I wonder if this is really https://github.com/moby/moby/issues/25450 - but maybe some parameters may be passed to tmux in order to avoid it?

**Comment by DarthSim** [comment]
Hi!
Unfortunately, I can't reproduce the issue with my docker images.
Overmind creates tmux session with the same size as your terminal. Have you tried to add `-e COLUMNS=$COLUMNS -e LINES=$LINES` to your command?

**Comment by davidkarlsen** [comment]
Sorry. Forgot to update. Yes. Adding those make it working. Also container needs to run with terminal and input

**Comment by brendandixon** [comment]
To which command do you add the `-e COLUMNS=$COLUMNS -e LINES=$LINES`?

**Comment by davidkarlsen** [comment]
to docker run - to define the env vars

**Comment by ibrahima** [comment]
I've been resizing my terminals each time I start a new docker session to work around this bug, but I just realized that when I start a session (using docker-compose exec container bash, in my case) it appears as if $COLUMNS is in fact defined (and set to 80), even though overmind complains about the width being too small.

I think hopefully the Docker bug might be fixed in the release that was just tagged a couple days ago (https://github.com/moby/moby/pull/37172 was mentioned as fixing a related issue on https://github.com/moby/moby/issues/25450).

**Comment by DarthSim** [comment]
> even though overmind complains about the width being too small

Overmind doesn't complain about anything here, this is a docker error. Somehow docker ignores the width of the tmux terminal, that's why providing $COLUMNS directly to docker fixes the issue.

**Comment by CatLight** [comment]
Got same error. 
>
       system | Tmux socket name: overmind-current-Fk0XkaXmiOHtkqStcnaRQO
       system | Tmux session ID: current
       web    | width too small
       web    | 

Using mina for deploy project and run commands. Here is the command:
`OVERMIND_SOCKET=tmp/sockets/.overmind.sock overmind start -f Procfile.prod`

Puma as server. It's single process in Procfile.prod for now:
` web:  bundle exec puma `

On local machine all is ok with any options. But if i run overmind on server directly( not with mina ) its working, but daemonizing process without choice and didnt create socket file.

I read about  ` -e COLUMNS=$COLUMNS -e LINES=$LINES`, but didn't understand where i must add them. I dont use docker.
