### ISSUE TITLE
disconnect from tmux?

### ISSUE THREAD

**Issue by subdigital** [DarthSim/overmind#32]
I find myself connecting to a process when I want to use `binding.pry` or the debugger, but is there a way to disconnect the tmux window without restarting the process?

(Not a huge deal, just a nuissance when I accidentally close the tmux window)

**Comment by DarthSim** [comment]
Hi! This is just thux, you can use `Ctrl+b` then `d` to disconnect from the session. Info about this was added to README by https://github.com/DarthSim/overmind/pull/24

**Comment by nicolas-brousse** [comment]
Hi!

I tried to use `Ctrl+b` then `d` but it print `^B^D` instead. I try to open a new `tmux` session in a fresh terminal and the shortcuts works in this case.

```
➜ ~ % overmind -v
Overmind version 1.2.1
```

I search on internet to found a reason, but I don't know why I have this behavior. Do you have any idea?

**Comment by mainangethe** [comment]
Hi @DarthSim , I wasn't able to see this in the README. Not sure why. Maybe we need to make it as a heading that this is how to Disconnect from a process.

**Comment by DarthSim** [comment]
@mainangethe `overmind connect` just launches tmux client attached to the Overmind session. I don't think we need a heading there since this is how tmux works, not how Overmind does.
