### ISSUE TITLE
Overmind displays unknown escape codes in output

### ISSUE THREAD

**Issue by ibrahima** [DarthSim/overmind#33]
Hi! I'm having an issue with Overmind in that it's showing unknown escape codes in the main overmind output. The weird thing is that when I run `overmind connect` to the subprocess that's outputting he escape codes, I don't see them in the output.

Basically, I'm using [guard](https://github.com/guard/guard) for running my unit tests when files are changed, and [capybara-inline-screenshots](https://github.com/buildkite/capybara-inline-screenshot) which adds inline screenshots for users of ITerm2. In other circumstances (running `guard` without Overmind), this output is just ignored, but it seems like somehow Overmind is mangling the output when it embeds it so that the terminal emulator ends up showing it. It looks like this:

```
guard     | ]1337;File=name=c2NyZWVuc2hvdF8yMDE0LTEwLTI3LTA3LTAwLTAyLjQ1Ny5wbmc=;inline=1:iVBORw0KGgoAAAANSUhEUgAABVYAAAMACAYAAADPPjzCAAAACXBIWXMAAAsTAAALEwEAmpwYAAAgAElEQVR4nOzddVxV9x/H8ReNgoiCKCZiYeuMqdjO7u7u2tQZU2frnLNnJ3Z3O7u7+2cXYM1ApeH3h/NO5FKKwrb38/Hgsd3v+cbn3HPO9fLhe77HJDQ0NJT/iMdPn+Lk6BjXYYiIiIhIHLvn+RQnh8RxHYaIiIiIxCE/n2ef3HbkqNGYx2IsIiIiIiIiIiIiIv8Y9o4pYtxm3txZAEqsioiIiIiIiIiIyH/Xi6fen9TONJbjEBEREREREREREfnXU2JVREREREREREREJIaUWBURERERERERERGJISVWRURERERERERERD6QJJlzlHWUWBURERERERERERH5y/...
```

except with many, many lines of output, since it's base64 encoding a PNG image (format documented at https://www.iterm2.com/documentation-images.html).

I'm getting this output because of this: https://github.com/buildkite/capybara-inline-screenshot/issues/1 but it seems like from their perspective the unknown escape codes are supposed to be ignored anyway. It's probably possible to make that library not output the inline screenshot data when the terminal is not ITerm2, but the way it is now it works inside VMs without any fiddling.

I am not sure whether the images do still get displayed with ITerm2, but it may be that it's broken there too, if the escape code is actually being mangled somehow.

If there's any way to fix this with Overmind, or to get it to ignore this output, that would be great. Thanks!

**Comment by DarthSim** [comment]
Hi!
I have tried to make this image output feature work in tmux, but I no success. It's hard to cut this from the output because this will slow down the entire output. Also for some reason, image data is splitted to multiple lines, and that makes cutting image data even harder. I'd not like to implement this complex fix because this affects a really small percentage of users.

I'd recommend you to disable capybara-inline-screenshot when you using overmind. You can do this by checking an environment variable and placing this variable in `.overmind.env`.

**Comment by ibrahima** [comment]
Thanks for looking into it! I just assumed that overmind is doing something incorrectly because if I do run `overmind connect guard` for instance, it works fine and ignores the unknown escape codes, as it's supposed to do. But yeah, I can just work around it for now.
