### ISSUE TITLE
Support starting multiple processes of a given type?

### ISSUE THREAD

**Issue by iand675** [DarthSim/overmind#34]
Foreman supports running multiple instances of a specification. This  can be useful for testing concurrent interactions and the like. The applicable flag is documented thusly:

```
-m, --formation
Specify the number of each process type to run. The value passed in should be in the format process=num,process=num
```

When the flag is used, the processes are suffixed with a number when labelling the output, e.g.:

```
$ overmind start -m web=2
web.1 | Started with pid 91384
web.2 | Started with pid 91385
```

**Comment by DarthSim** [comment]
Hi Ian,

Didn't think this feature would be useful for anyone in development :) Added to the latest release https://github.com/DarthSim/overmind/releases/tag/v1.2

**Comment by iand675** [comment]
Thanks! Just a side note, but looks like the version flag in the new release still says 1.1.1

**Comment by DarthSim** [comment]
Thanks for pointing on this! Fixed
