### ISSUE TITLE
Overmind ignores variables set in `.env.local` that are already set in `.env`

### ISSUE THREAD

**Issue by constantm** [DarthSim/overmind#35]
Firstly, Overmind is amazing! Then, it seems to make variables declared in `.env` immutable, and do not update them when loading `.env.local`. 

For example, with the following config, `REDIS_HOST` would be `redis` when running the app:

.env
```
REDIS_HOST=redis
```

.env.local
```
REDIS_HOST=localhost
```

A workaround for this is running: `OVERMIND_ENV=.env.local overmind s`.

**Comment by DarthSim** [comment]
Looks like it's your local issue, I can't reproduce it. Overmind reloads every variable that specified in env files, and it loads a file from `OVERMIND_ENV` last. Please make sure about naming.

Procfile.test
```
redis_host: echo REDIS_HOST is $REDIS_HOST
```

```
$ OVERMIND_ENV=.env.local overmind s -f Procfile.test                                                                       16:17
system     | Listening at ...
system     | Tmux socket name: overmind-overmind-QYXtYFV8I_dsjtP6fysYJu
system     | Tmux session ID: overmind
redis_host | Started with pid 95600...
redis_host | REDIS_HOST is localhost
redis_host | Exited
```

**Comment by constantm** [comment]
Thanks for checking this out!

It looks like the problem is that I expected it to work like the Ruby implementation of `dotenv`, which loads `.env`, followed by `.env.local`. However, since you're using the Go implementation, it only loads `.env`, and ignores `.env.local` entirely. 

Since Overmind is not written specifically for Ruby environments, I'll go ahead close this issue.

**Comment by DarthSim** [comment]
When you set `OVERMIND_ENV=.env.local`, overmind uses it as a last env file, so it should work like you expect. Unfortunately, I have no idea why it works for me and doesn't work for you :(

**Comment by constantm** [comment]
`OVERMIND_ENV=.env.local overmind s` works perfectly fine. :)

I expected it to load `.env.local` by running just `overmind s`, which it doesn't.

**Comment by DarthSim** [comment]
Oh, got it :) Yeah, you're right
