### ISSUE TITLE
Does overmind respond to SIGINT?

### ISSUE THREAD

**Issue by jackkinsella** [DarthSim/overmind#37]
I noticed on macos that when I press Control-C (i.e. send SIGINT), overmind doesn't terminate every process (in particular, webpack-dev-server, which may well be misbehaving 😈 ). Instead overmind says "Interrupting..." but hangs forever. Running `overmind kill .overmind.sock` from another terminal session finishes the job perfectly though, even when it's already hanging.

So I'm wondering if overmind is intended to respond to SIGINT or if `overmind kill` is always needed?

Here was my Procfile FYI. Rails 5.2 

```
web: bin/rails server -p 3000
worker:  bin/rake jobs:work
webpacker: bin/webpack-dev-server
guard: bundle exec guard
elasticsearch: elasticsearch
```

PS very cool piece of software. It addresses all the gripes I had with using Foreman in a modern Rails stack (logs messed up, challenging to inject a debugger)

*Update*: Pressing Control-C in `foreman` running the same Procfile terminates the processes as expected, though the output suggests that after failing with SIGINT, it escalated to SIGKILL five seconds later.

**Comment by DarthSim** [comment]
Hi,

When you sent `SIGINT` to Overmind, it sends it to all running processes. The second `SIGINT` will make Overmind to send `SIGKILL` to all misbehaving processes. Also, if some processes misbehave after the first `SIGINT`, Overmind will kill 'em all after a short timeout.

I had many headaches with `webpack-dev-server` too, so I developed Overmind to make sure it will kill that bad boy properly :)

**Comment by kripper** [comment]
When using `overmind connect <servicename>` and pressing CTRL+C, the signal shoudln't be sent to all processes. Currently the .socket file is removed so connecting to other services is not possible anymore.

**Comment by DarthSim** [comment]
@kripper By using the `overmind connect <servicename>` command, you connect to a Tmux session. Pressing CTRL+C in a Tmux session sends SIGINT to the process you're connected to. By default, Overmind shuts down all the processes if any of them exit.

In other words, the behavior you've described is expected.
