### ISSUE TITLE
Unable to send input to child processes

### ISSUE THREAD

**Issue by ibrahima** [DarthSim/overmind#4]
First of all, thanks for creating this! It seems like exactly what I've always wanted - a more reliable way of running tasks in a Procfile, where I can still communicate with the child processes.

Unfortunately, I just tried it out with my Rails app and I can't seem to actually communicate with any of the child processes - when I run `overmind connect rails` or other processes, any input I enter doesn't go to the child, it just gets echoed. When I try to send command sequences like ctrl-C, I just see `^C`, and `^M` when hitting enter, etc. Normally when using tmux I don't have to do anything special to send input to the child, so I'm wondering what I'm doing wrong here. Or did I misunderstand what overmind does?

Procfile is pretty generic:

```
rails:  bin/rails s
guard:  bundle exec guard start --no-interactions -w app config spec lib db vendor
worker: bundle exec sidekiq -C config/sidekiq.yml
mailcatcher: bundle exec mailcatcher -f --ip 0.0.0.0 --smtp-port 6666
webpack: npm run server
storybook: npm run storybook
```

Running Overmind 1.0.7 on a Rails 4 app on Ubuntu 14.04 inside Vagrant/VirtualBox (built tmux 2.5 from source, as it seems like the tmux 1.8 that Trusty comes with isn't supported by overmind).

Any help would be appreciated. Thanks again!

One addition: If I make a new window in tmux with `C-b c`, I can send input to that shell, so it seems like it's something to do with what Overmind is doing with ptys?

I also see the same behavior on my Linux host which is Ubuntu 17.04.

**Comment by redross** [comment]
Have the same issue. ctrl+enter does submit it properly, but it's not working as a regular terminal (command history doesn't work, navigation arrows don't work, etc.)

**Comment by ibrahima** [comment]
Hmm, interesting. For me, I can type stuff, and then use <kbd>Ctrl+J</kbd>to submit that line to the child process, but that's not what I'd expect. <kbd>Ctrl+enter</kbd> does nothing though. But for instance, I can send SIGINT to a child using <kbd>Ctrl+C</kbd> followed by <kbd>Ctrl+K</kbd> which is slightly cumbersome but at least usable.

**Comment by DarthSim** [comment]
Hi! It's definitely an issue. The problem is probably in a wrapper which Overmind uses to redirect output to the main process. I need some time to investigate this.

**Comment by DarthSim** [comment]
Please check the latest release. I've tested in on my Ubuntu server, and it seems to work fine.

**Comment by ibrahima** [comment]
Awesome! Works for me!
