### ISSUE TITLE
Feature request: configure the signal used to stop/restart a particular process

### ISSUE THREAD

**Issue by smaximov** [DarthSim/overmind#41]
Erlang/Elixir apps are usually started from withing Erlang or Elixir shell (`erl` and `iex`, respectively) in development. `erl` installs a SIGINT handler which displays the so called "BREAK" menu instead of stopping the process:

```
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
```

To actually stop the shell, the user have to select the `abort` command (<kbd>a</kbd>)  or send SIGINT again. Elixir shell (`iex`) adopts this behavior.

Consider the following Procfile which runs a RabbitMQ server and a toy Elixir app:

``` yaml
broker: rabbitmq-server
consumer: cd consumer && iex -S mix
```

Stopping processes run by this Procfile either by sending SIGINT (<kbd>Ctrl</kbd>+<kbd>C</kbd>) to the overmind process or by running `overmind kill` works fine because overmind also sends SIGKILL shortly after sending SIGINT (or so it seems). But in order to restart the `consumer` process I have to run `overmind restart consumer` twice.

The solution would be to send SIGQUIT instead ([4.4  How do I quit the Erlang shell?][sigquit]). Can you add a way to specify the signal used to restart a process? Something like this:

``` bash
$ overmind restart process1 [process2 process3 ...] \
      --stop-signal=process1:SIGQUIT[,process2:SIGINT,process3:SIGTERM...]
$ OVERMIND_STOP_SIGNAL=process1:SIGQUIT[,process2:SIGINT,process3:SIGTERM...] \
      overmind restart process1 [process2 process3 ...]
```

[sigquit]: http://erlang.org/faq/getting_started.html#idp31936144

**Comment by RudyOnRails** [comment]
I wonder if this would also satisfy a feature request I thought of today - and that is to be able to stop a specific process. At times I want to just stop the `rails` process and not everything in our Procfile, for when we need to run migrations and such (in our pre-alpha phase right now we tweaking migration files and run an alias of `redodb` often.

**Comment by smaximov** [comment]
There was a PR for this: #28.

**Comment by DarthSim** [comment]
Added to [v2.0](https://github.com/DarthSim/overmind/releases/tag/v2.0.0)

The `stop` command is also added to v2.0

**Comment by smaximov** [comment]
Thanks @DarthSim, just tested v2.0.0 and it works like a charm!
