### ISSUE TITLE
.env file parsing and escape characters/interpolation

### ISSUE THREAD

**Issue by matsrietdijk** [DarthSim/overmind#44]
After upgrading from 1.1.1 to 1.2.1 environment variables are parsed differently (incorrectly?).

Environment variables enclosed by single quotes (`'`) would not be subject to interpolation in 1.1.1 but are in 1.2.1, eg:

```
#.env
A='VALUE'
B='$A'
```

With `1.1.1`:

```
> echo $A
STRING
> echo $B
$A
```

With `1.2.1`:

```
> echo $A
STRING
> echo $B
STRING
```

The issue I experience is that most other .env parsers do not interpolate on a single quote enclosed value. So for instance running a Ruby on Rails application with `overmind` or just `rails s` result in the application being run with different environment variables.

**Comment by DarthSim** [comment]
It was a bug in `github.com/joho/godotenv`. Fixed in [v2.0](https://github.com/DarthSim/overmind/releases/tag/v2.0.0)
