### ISSUE TITLE
Support taking PORT from .env

### ISSUE THREAD

**Issue by paneq** [DarthSim/overmind#45]
Here is my config:

```
$ cat Procfile 
web: bin/rails s -p $PORT
webpack: yarn start

$ cat .env
PORT=3003
```

But `overmind` ignores the `PORT` from `.env` and I had to create `.overmind.env` with the same config.

```
$ cat .overmind.env 
OVERMIND_PORT=3003
```

It would be nice if it worked out of the box.

Other than that, I am super happy with `overmind` and thank you for creating it! It's the only issue I've ever encountered after 3 months of using it.

**Comment by DarthSim** [comment]
Added to [v2.0](https://github.com/DarthSim/overmind/releases/tag/v2.0.0)

**Comment by paneq** [comment]
That was fast. Thank you!
