### ISSUE TITLE
Start overmind with option except specified processes

### ISSUE THREAD

**Issue by Yegorov** [DarthSim/overmind#49]
Overmind can ran only specified processes, defined in [`OVERMIND_PROCESSES`](https://github.com/DarthSim/overmind#running-only-the-specified-processes)
It possible start overmind with exclude specified processes?
For example, in [foreman](https://ddollar.github.io/foreman/#EXAMPLES) it's done like this: `foreman start -m all=1,worker=0`
Сan you add a `OVERMIND_EXCEPT_PROCESSES` variable in the future?

**Comment by DarthSim** [comment]
You can do this just the same way with Overmind. You can also use `OVERMIND_FORMATION` variable to specify formation.

**Comment by DarthSim** [comment]
Ah, didn't notice `all`. Overmind launches one instance of each process by default. So you can do `overmind s -m worker=0`

**Comment by Yegorov** [comment]
Ok, thanks for fast answer. It would be good if it were in the README.
