### ISSUE TITLE
Better way to deal with unexpected termination

### ISSUE THREAD

**Issue by bhrutledge** [DarthSim/overmind#50]
First, I love Overmind. Thank you for all the work!

This is a small issue, maybe solved by documentation. Most of the time, I exit `overmind start` via `Ctrl-C` (i.e., `SIGINT`). However, sometimes I'll inadvertently close the terminal. This leaves the processes running in a tmux session, and an orphan `.overmind.sock`. So, the next time I run `overmind start`, I get things like:

```console
$ overmind start
overmind: it looks like Overmind is already running. If it's not, remove .overmind.sock and try again

$ pgrep -fl overmind
39965 tmux -CC ...
39966 /bin/sh /var/folders/m3/...
39967 /bin/sh /var/folders/m3/...
```

To recover from this, I run:

```
$ pkill -fl overmind; rm -f .overmind.sock 
```

It'd be nice if I could reattach to the running session, and/or clean it up with an Overmind command.

**Comment by marckohlbrugge** [comment]
I run into this all the time Here's what it looks like:

```bash
% overmind start
system | Tmux socket name: overmind-foobar-md7CP2HbTfJJglZ105B-cO
system | Tmux session ID: foobar
system | Listening at ./.overmind.sock
overmind: it looks like Overmind is already running. If it's not, remove ./.overmind.sock and try again
```

I figure it's already running in one of my tabs, so I do:

```bash
% overmind restart
overmind: dial unix ./.overmind.sock: connect: connection refused
```

Oh, looks like it's not running after all. Must be a stale .sock file.

```
% rm .overmind.sock
% overmind start
```

It gets a bit repetitive doing this over and over again.

Is there a way to have `overmind start` check if it's indeed still active and it not delete any stale sock files?

**Comment by DarthSim** [comment]
I hope, #86 fixes this. I honestly don't know a better way to handle this.

**Comment by bhrutledge** [comment]
This fixed it for me in v2.2.0. Thanks!

**Comment by stavalfi** [comment]
hi @DarthSim @bhrutledge - it doesn't work for mac. is this the expected behavior?

**Comment by ibrahimkonuk** [comment]
> hi [@DarthSim](https://github.com/DarthSim) [@bhrutledge](https://github.com/bhrutledge) - it doesn't work for mac. is this the expected behavior? the socket file is not deleted if i close the tab.
> 
> my workaround is to make a trap:
> 
> overmind start & OVERMIND_PID=$!
> 
> trap "rm -f .overmind.sock" EXIT
> 
> wait "$OVERMIND_PID" 2>/dev/null || true
>  * sometimes the sub-processes still alive as well

Thanks @stavalfi! It solved my problem on Mac!
