### ISSUE TITLE
Tmux pane size limited to 80x24

### ISSUE THREAD

**Issue by brovikov** [DarthSim/overmind#51]
Hi!

Thanks for the great tool! Having funny time using it last several days. Good job!

However I have a problem with pane size which limited to subject size with notice: 
`(size 80x24 from a smaller client)`

I'm trying to resize it eg like described [here](https://stackoverflow.com/questions/16145078/in-tmux-can-i-resize-a-pane-to-an-absolute-value) with any luck.

Interesting that tmux running fullscreen when I just run it as `tmux` without any args. But when I connect over `overmind c ...` it limits size. 

I'm running under Ubuntu 16.04, zsh, tmux 2.1

Any ideas?

![tmux](https://user-images.githubusercontent.com/4372434/55013620-243a6f00-4ff2-11e9-99bf-a24c100e82af.png)

**Comment by DarthSim** [comment]
Hi,

Thanks for catching this. In tmux <2.6 control mode client is treated as a usual client with the default size. Tmux 2.6 fixes this behavior. Anyway, I patched Overmind to resize control mode client to the size of the current terminal. Please check out v2.0.2.

**Comment by brovikov** [comment]
Great thanks, @DarthSim ! v2.0.2 did the trick! Now it works good for me and I'm gong to close this issue! Once again - thanks for the great tool!
