### ISSUE TITLE
An option to run in detached/daemon mode

### ISSUE THREAD

**Issue by alecgorge** [DarthSim/overmind#53]
Thank you for Overmind! It is great!

Would it be feasible to add a `-d/--detach` option that launches overmind but doesn't automatically show the output of all commands. I'd love to have overmind running in the background, keeping things alive without needing to keep it open. Right now what I do is start overmind in a tmux session and then disconnect from it to ensure it keeps going after I close my SSH connection.

`overmind connect` (with no arguments) could be used to bring that back to the foreground.

This could be as simple as starting the main output in a disconnected tmux session that would show up in `tmux ls`

**Comment by DarthSim** [comment]
Hi,

[v2.0.3](https://github.com/DarthSim/overmind/releases/tag/v2.0.3) supports daemonization. Use `-D` flag to run Overmind in daemon mode, `echo` command for echoing logs to STDOUT, and `quit` command for quitting daemonized Overmind.
