### ISSUE TITLE
Reconfigure tmux on overmind boot

### ISSUE THREAD

**Issue by brasic** [DarthSim/overmind#55]
I use tmux as my terminal multiplexer, so I thought overmind would be a great fit.  But running `overmind connect` inside an existing tmux session results in a nested session.  Nesting tmux sessions is fine, but it's only really usable if the inner and outer sessions have different prefix keys.  I couldn't find a way to achieve this automatically with overmind.  Here are some possible ways:
 - optionally pass `-f <alternate config path>` to overmind's tmux invocation, so that overmind's tmux session is configured with a different prefix from my "everyday" `tmux.conf`.
 - a way to run arbitrary commands at overmind launch via an rcfile of some kind, so I can run `tmux send-keys` to rebind the prefix
 - some other thing I haven't thought of, maybe one that already exists?

I'd be happy to open a PR to implement one of the above if a maintainer is interested!

**Comment by DarthSim** [comment]
Hi,

[v2.0.3](https://github.com/DarthSim/overmind/releases/tag/v2.0.3) supports `-F` flag for an alternative tmux config.

**Comment by brasic** [comment]
That is perfect, thanks so much!

**Comment by tannakartikey** [comment]
@brasic can you please share your Overmind tmux config? I use Tmux too but not pro enough to make both work. 

Thanks
