### ISSUE TITLE
Overmind overrides action cable port

### ISSUE THREAD

**Issue by tim-millar** [DarthSim/overmind#56]
Having an issue where we set the action cable domain and port in an initializer, but overmind (seemingly) keeps the domain but overrides the port and sets it to 5100.

We are starting the rails server in a procfile like this:

```bin/rails server -p 3000```

We're expecting action cable to be accessed on the same port

**Comment by DarthSim** [comment]
Overmind sets `PORT` env variable for each process as is described [here](https://github.com/DarthSim/overmind#specifying-the-ports). It's a common behavior for the most Procfile launchers. Looks like your Action Cable initializer uses this variable.

**Comment by lastobelus** [comment]
but, can we override? For example, in this Procfile:

```
web: bundle exec rails s
cypress: CYPRESS_BASE_URL=http://${APP_DOMAIN}:${PORT} yarn cypress open --project ./spec
anycablego: anycable-go --host=$ANYCABLE_DOMAIN --port=$ANYCABLE_PORT
```

the `web` and `cypress` processes should have the SAME value for PORT. Is there a way to have overmind just respect the contents of the specified `.env`?

**Comment by tim-millar** [comment]
@lastobelus that's helpful - I set
```
+PORT=3000
+OVERMIND_PORT=3000
+OVERMIND_PORT_STEP=0
```
in `.overmind.env`, which solved the problem.
