### ISSUE TITLE
Cannot get overmind to start because of missing sock file

### ISSUE THREAD

**Issue by damienlethiec** [DarthSim/overmind#63]
Hi there,

I have been using Overmind successfully for the last year ! Thanks so much for the awesome tool.

Today, I did a new `rails new` and tried to get overmind up and running with my new app (Rails 6.0.0). I created a Procfile and a Procfile.dev. Tmux and Overmind (2.0.3) are installed.

However, I cannot make overmind work. I get 2 errors depending on the commands used:

`overmind start` give me the following:
```
system  | Tmux socket name: overmind-shopify-magistor-connector-RfVK8NchYmkhRJOm7rUAQR
system  | Tmux session ID: shopify-magistor-connector
system  | Listening at /Users/damienlethiec/code/damienlethiec/ProjetsPros/AventureBio/Consulting/Ensovo/shopify-magistor-connector/.overmind.sock
overmind: listen unix /Users/damienlethiec/code/damienlethiec/ProjetsPros/AventureBio/Consulting/Ensovo/shopify-magistor-connector/.overmind.sock: bind: invalid argument
```

All the other commands give me the following:
```
overmind: dial unix ./.overmind.sock: connect: no such file or directory
```

Do you know why overmind.sock does not get created? How can I make it works?

Thanks so much in advance,
Damien

**Comment by damienlethiec** [comment]
Ok, I got closer to a solution. I actually cannot launch overmind for new Rails apps with a name more than 6 characters long. I have absolutely no idea why. Would you have any clue?

**Comment by DarthSim** [comment]
Hi,

TIL that maximum allowed path length for unix-socket is 104. Your socket path is 120 chars length. I'll think of how to solve this. As a temporary solution, I can offer you to use a custom socket path.

> All the other commands give me the following:
> overmind: dial unix ./.overmind.sock: connect: no such file or directory

`overmind start` creates a socket file, and all other commands connect to it. If you can't run `overmind start`, there is no socket created.

**Comment by damienlethiec** [comment]
Thanks a ton ! No worries for now, but great if you can fix it in the future :)

Have a great day !

**Comment by DarthSim** [comment]
I decided to keep going with unix sockets, but v2.1.0, does not expand the socket path, so it should work for you.
