### ISSUE TITLE
downloaded binary, what's next?

### ISSUE THREAD

**Issue by phangs** [DarthSim/overmind#65]
Install guide says 1 option is to download the binary release nothing else.

Using it for lucky framework yet lucky dev command says no process manager found

**Comment by ermolaev** [comment]
```sh
curl -L https://github.com/DarthSim/overmind/releases/download/v2.1.0/overmind-v2.1.0-linux-amd64.gz > overmind.gz
gunzip overmind.gz
mv overmind /usr/local/bin
chmod +x /usr/local/bin/overmind
```

`overmind start` run processes in your Procfile
