### ISSUE TITLE
Bug: Overmind is not update

### ISSUE THREAD

**Issue by ricardopacheco** [DarthSim/overmind#66]
This problem happens in ubuntu/osx. When i run `go get -u -f github.com/DarthSim/overmind`, returns:

```
go/src/github.com/DarthSim/overmind/cmd_restart.go:21:55: cannot use c.Args() (type cli.Args) as type []string in argument to strings.Join
go/src/github.com/DarthSim/overmind/cmd_run.go:21:21: invalid operation: c.Args()[0] (type cli.Args does not support indexing)
go/src/github.com/DarthSim/overmind/cmd_run.go:26:18: cannot slice c.Args() (type cli.Args)
go/src/github.com/DarthSim/overmind/cmd_stop.go:21:52: cannot use c.Args() (type cli.Args) as type []string in argument to strings.Join
go/src/github.com/DarthSim/overmind/main.go:18:23: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in return argument:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/DarthSim/overmind/main.go:20:3: unknown field 'EnvVar' in struct literal of type cli.StringFlag
go/src/github.com/DarthSim/overmind/main.go:36:18: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/DarthSim/overmind/main.go:36:37: unknown field 'EnvVar' in struct literal of type cli.StringFlag
go/src/github.com/DarthSim/overmind/main.go:37:18: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/DarthSim/overmind/main.go:37:40: unknown field 'EnvVar' in struct literal of type cli.StringFlag
go/src/github.com/DarthSim/overmind/main.go:37:18: too many errors
```

Go version go1.13.4 darwin/amd64
Go version go1.13.5 linux/amd64

**Comment by DarthSim** [comment]
`GO111MODULE=on  go get -u github.com/DarthSim/overmind` should work. I'll update README

**Comment by DarthSim** [comment]
I have updated the package name, use `GO111MODULE=on go get -u github.com/DarthSim/overmind/v2`

**Comment by piotr-galas** [comment]
I am not so experienced in linux. 
Is that command enough to make everything works `GO111MODULE=on go get -u github.com/DarthSim/overmind/v2`

After runnnig it I cannot access to `overmind`

`zsh: command not found: overmind`

Am I missing something?  should I run it in the same directory I downloaded source?


On maxos it works great! I would like to use it on my private ubuntu as well.

**Comment by piotr-galas** [comment]
I finally manage to install it. 

`go` command didn't work to me. I finally downloaded binary instead, added 777 permission and moved the file  to `/usr/local/bin` 

Probably obvious for most users but not for me. :)

**Comment by DarthSim** [comment]
@piotr-galas `go get` puts the binary into `$GOBIN` or into `$GOPATH/bin` in case the first is not set. Looks like you need to add it to your `PATH`.

Downloading precompiled binaries is an easier way to install Overmind for sure.
