### ISSUE TITLE
Overmind not properly passing PORT env on restart

### ISSUE THREAD

**Issue by piotrb** [DarthSim/overmind#68]
My Procfile has

```
web: bundle exec ./bin/rails server -p $PORT
```

in it .. 

Everything works great on start .. 

But when I restart the web process I get an error from the server something along the lines of

`No value provided for option '--port'`

Which to mean sounds like somehow $PORT is not being evaluated properly on restart .. 

This used to work a few versions back I'm pretty sure ..

**Comment by pnomolos** [comment]
Looks like it's also not passing `OVERMIND_STOP_SIGNALS` properly, as I can only restart my web process once - it sends `SIGUSR2` the first time, but `SIGINT` the next time.

**Comment by DarthSim** [comment]
Fixed in v2.1.1
