### ISSUE TITLE
socket under vagrant shared volumen

### ISSUE THREAD

**Issue by kascote** [DarthSim/overmind#7]
Hi, I'm testing overmind and work great! but I has a little issue.

I'm working under Vagrant and by default it create a share under /vagrant pointing to the project's directory (1). 
When I try to run `overmind s` it return an error that can't create the socket file. I assume this is because of the shared mount.
```
vagrant@ntfx2 in /vagrant/dev/cga/bec on master!
$ overmind s
overmind: listen unix /vagrant/dev/cga/bec/.overmind.sock: bind: operation not permitted
```

This obligate me to use the `-s` flag on every command. Could you add an environment variable to define the socket file ?

TIA

(1) https://www.vagrantup.com/docs/synced-folders/

**Comment by DarthSim** [comment]
Hi,
Sorry for the huge delay. Env variable added to the latest release https://github.com/DarthSim/overmind/releases/tag/v1.0.9
PR to Homebrew is waiting for merge https://github.com/Homebrew/homebrew-core/pull/20917

**Comment by lebogan** [comment]
Newbie question: how is this actually fixed? I get that error running on a shared vagrant volume but it works correctly when I run it in the vm itself.

**Comment by stotler** [comment]
What is the environment variable to set the sock file?

**Comment by kascote** [comment]
https://github.com/DarthSim/overmind#specifying-a-socket
