### ISSUE TITLE
Feature proposal: Allow to interract with overmind from a subfolder

### ISSUE THREAD

**Issue by simonc** [DarthSim/overmind#77]
Hi,

I recently switch from `heroku local` to Overmind and it's magical, thank you for this great tool!

I'd like to propose the addition of a new feature: allowing to run commands from sub-folders of the one containing the `.overmind.sock` file.

Working on a multi-app project, be it API+SPA or micro-services, you usually end up being inside of an app's folder because that's where you work with it or with git, etc.

Being able to restart/connect to one of the processes of the project while in a sub-folder would greatly smooth the workflow IMHO.

I don't really know Go otherwise I would have proposed a PR but I'm open to helping in any other way I can.

Thanks! ❤️

**Comment by DarthSim** [comment]
Hey! Glad you like Overmind!

This feature requires a very careful revision of lots of things such as Procfile detection, socket path detection, .env file loading as so on. However, if your goal is only to interact with running Overmind from subfolders, you can add `.overmind.env` file to desired subfolders with something like `OVERMIND_SOCKET="../.overmind.sock"`. This will tell Overmind to use a socket from the parent folder.

**Comment by simonc** [comment]
That's an interesting workaround 😊 thanks!
