### ISSUE TITLE
Reloading env variables

### ISSUE THREAD

**Issue by vvo** [DarthSim/overmind#78]
Hi there, I would like to be able to reload overmind to take into account new env variables without having to completely kill it and restart it. Did you ever think about this use case? Thanks.

PS: I love overmind. I think it's the best but most underknown .env/process manager ever created and I try to share it as much as possible.

**Comment by DarthSim** [comment]
Hey! Glad you love Overmind!
Even if I manage to rewrite env variables of the running tmux server (that seems problematic for me), they won't be rewritten for already running processes. And restarting all processes doesn't look different from restarting the whole overmind.

**Comment by vvo** [comment]
Indeed that's very similar and fine for me, thanks again!
