### ISSUE TITLE
Overmind tmux session is not listed in general tmux session list

### ISSUE THREAD

**Issue by sevenmaxis** [DarthSim/overmind#79]
I have multiple tmux sessions. I detach from them and start overmind in daemon mode.
The command `tmux ls` doesn't show the overmind's session, I have to connect to it via tmux socket, which is not convenient.

**Comment by radiantshaw** [comment]
I came across this same situation. Overmind doesn't get listed when I do `tmux ls`. This is not an issue for me, but I'm curious if anyone knows why this is the case.

**Comment by Envek** [comment]
I believe that it was made on purpose to discourage people from tinkering with overmind's tmux session on the first place. Please don't touch overmind's tmux.

Also as a bonus it additionally isolates tmux sessions of different overmind sessions from each other (and user sessions) reducing risk of messing things up in case of a bug.

**Comment by DarthSim** [comment]
Overmind launches a separate Tmux server on its own socket.

A session created in the existing Tmux server will have environment variables defined as they were defined at the start of the server. Launching a new server allows to pick up up-to-date env variables.
