### ISSUE TITLE
Multiplex-less 

### ISSUE THREAD

**Issue by pirj** [DarthSim/overmind#8]
I use a simple script to run each item from Procfile:
```
grep --invert-match '#' < Procfile | sed -e 's/^[^:]*: //' | xargs -I {} tmux split-window -v \; send-keys '{}' 'C-m' && tmux select-pane -t 1 \; send-keys 'C-d' \; select-layout even-vertical
```

Example output for `Procfile` like this:
```
web: watch ls
workers: watch date
node: watch ls
monotor: watch date
```

![screen shot 2017-09-28 at 17 49 57](https://user-images.githubusercontent.com/6916/30973560-140eb11e-a476-11e7-9a65-ca4a4e867c11.png)

I can selectively maximize/minimize, rearrange panes.
It's also much more convenient from the point of STDIN when all processes are run in their own panes if you decide to send signals or set breakpoints and use REPL.

Not an issue or a pull request, just would like to know what do you think.

**Comment by DarthSim** [comment]
Hi,
I had this way in mind when I developed overmind. I don't really like panes because usually there is one process that generates the most output, and some processes that output time by time& I don't like when that processes eat my terminal space without need.
But if it works for you, who am I to forbid you using plain tmux? :)

**Comment by pirj** [comment]
I'll just leave it here for those who took the bare tmux path:
`C-b z` to toggle pane zoom

For `foreman` it used to share STDIN across running processes and that was quite a pain if you e.g. set a breakpoint. To type something you had to repeat it several times, and you didn't see your input because of the scrolled output of the other processes.
Is overmind able to properly dispatch input?

**Comment by DarthSim** [comment]
Yup, that's exactly why overmind was developed. You can connect to a process with `overmind c process` and do whatever you want with it.

**Comment by qwIvan** [comment]
> Yup, that's exactly why overmind was developed. You can connect to a process with `overmind c process` and do whatever you want with it.

A convenient way is allow overmind to connect multi process then launcher a tmux process attach multi session in split window.
