### ISSUE TITLE
Support for scaling processes

### ISSUE THREAD

**Issue by ktchernov** [DarthSim/overmind#85]
It would be great to be able to scale a single Procfile line to run as multiple processes.

For example `Procfile`:

`worker: /usr/local/bin/command.sh`

But to be able to tell overmind to launch N number of these. 

In Heroku this can be done with a `ps:scale N` command. In `supervisord`, there is a way to specify `numprocs` parameter per program definition.

**Comment by kalekseev** [comment]
If you look at the output of `overmind s -h` you will find this option

```
   --formation value, -m value     Specify the number of each process type to run. The value passed in should be in the format process=num,process=num. Use 'all' as a process name to set value for all processes [$OVERMIND_FORMATION]
```

Would be good to have this mentioned in the README

**Comment by DarthSim** [comment]
Added formation docs to README https://github.com/DarthSim/overmind#scaling-processes-formation
