### ISSUE TITLE
maybe not check the tmux though another command

### ISSUE THREAD

**Issue by mumutu66** [DarthSim/overmind#96]
https://github.com/DarthSim/overmind/blob/39a405d03f4873524fca545d8d52253ba0c1e123/start/command.go#L177

In case the `which` command is missing overmind will fail even tmux has been installed

**Comment by DarthSim** [comment]
Sorry, I don't know a better way to check tmux existence :(

**Comment by DarthSim** [comment]
v2.2.1 checks tmux with `tmux -V` instead of `which tmux`. Hope this will help.

**Comment by mumutu66** [comment]
it's great
